# Используем базовый образ Python
FROM python:3.9

# Обновляем пакеты и устанавливаем ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Копируем requirements.txt
COPY requirements.txt .

# Копируем остальные файлы в контейнер
COPY . /app/

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Определяем команду, которая будет выполнена при запуске контейнера
CMD [ "python", "Podcast_bot.py" ]