# minimum supported Python version
target-version = "py310"
# maximum line lengt
line-length = 130

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
]

[format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

[lint.isort]
known-third-party = ["aiogram", "aiofiles", "aiobotocore", "motor", "audio_lib", "pydantic"]
